export enum ContentType {
    JSON = "application/json",
    TEXT = "text/plain",
    HTML = "text/html",
    XML = "application/xml",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    FORM_DATA = "multipart/form-data",
    JAVASCRIPT = "application/javascript",
    CSS = "text/css",
    CSV = "text/csv",
    ICO = "image/vnd.microsoft.icon",
    JPEG = "image/jpeg",
    PNG = "image/png",
    GIF = "image/gif",
    SVG = "image/svg+xml",
    PDF = "application/pdf",
    ZIP = "application/zip",
    MP3 = "audio/mpeg",
    MP4 = "video/mp4"
}